packages:
  - ./
  - playground/

allowUnusedPatches: true

catalog:
  '@alanscodelog/eslint-config': ^6.3.1
  '@alanscodelog/semantic-release-config': ^6.0.2
  '@alanscodelog/tsconfigs': ^6.2.0
  '@alanscodelog/utils': ^6.0.2
  '@nuxt/eslint-config': ^1.15.1
  '@nuxt/kit': ^4.3.1
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.3.1
  '@nuxt/test-utils': ^3.23.0
  '@witchcraft/nuxt-logger': ^0.0.10
  '@witchcraft/nuxt-utils': ^0.3.6
  '@witchcraft/ui': ^0.3.24
  changelogen: ^0.6.2
  concurrently: ^9.2.1
  defu: ^6.1.4
  electron: ^37.10.3
  electron-builder: ^26.8.1
  es-toolkit: ^1.44.0
  eslint: ^9.39.2
  husky: ^9.1.7
  json5: ^2.2.3
  nuxt: ^4.3.1
  thread-stream: ^3.1.0
  typescript: ^5.9.3
  unplugin-icons: ^22.5.0
  vite-plugin-electron: ^0.29.0
  vite-plugin-externalize-deps: ^0.9.0
  vitest: ^3.2.4
  vue-tsc: ^3.2.4

patchedDependencies:
  '@nuxt/module-builder': patches/@nuxt__module-builder.patch

settings:
  catalogMode: strict
  cleanupUnusedCatalogs: false
