export { getPaths }from "./getPaths.js"
export { createNuxtFileProtocolHandler } from "./createNuxtFileProtocolHandler.js"
export { useNuxtRuntimeConfig } from "./useNuxtRuntimeConfig.js"
export { STATIC }from "./static.js"
export { useDevDataDir } from "./useDevDataDir.js"
export { registerDevtoolsShortcuts } from "./registerDevtoolsShortcuts.js"
